# Generated by Django 5.1.3 on 2024-12-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_alter_contact_email_alter_contact_full_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="mobile",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
