# Generated by Django 5.1.3 on 2024-12-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_alter_contact_mobile_alter_profile_mobile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200, null=True)),
                ("email", models.CharField(max_length=200, null=True)),
                ("mobile", models.CharField(blank=True, null=True)),
                ("message", models.TextField(null=True)),
                ("updated_cv", models.FileField(upload_to="cv_files/")),
                ("add_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
