# Generated by Django 5.1.3 on 2024-12-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0005_gallery_roomimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roomimage",
            name="room_type",
        ),
        migrations.AddField(
            model_name="roomimage",
            name="room_type",
            field=models.ManyToManyField(to="rooms.roomtype"),
        ),
    ]
