# Generated by Django 5.1.3 on 2024-12-05 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0006_remove_roomimage_room_type_roomimage_room_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roomimage",
            name="room_type",
        ),
        migrations.AddField(
            model_name="roomimage",
            name="room_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rooms.roomtype",
            ),
        ),
    ]
