# Generated by Django 5.1.3 on 2024-12-07 13:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0008_banners_controlpanel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Banners",
        ),
        migrations.DeleteModel(
            name="ControlPanel",
        ),
    ]
